version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - yb_hackathon-postgresql:/var/lib/postgresql/data
    env_file:
      - .envs/postgresql
    environment:
      # set `${PGDATA}` to a subdirectory because PostgreSQL needs this
      # directory to be empty and there is already `.gitkeep` file there
      - PGDATA=/var/lib/postgresql/data/postgresql_data

  app: &app
    container_name: yb_hackathon-app
    build:
      context: .
      dockerfile: ./docker/local/backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/general
      - .envs/flask
      - .envs/celery
      - .envs/postgresql
    volumes:
      - ./backend:/app
      - ./shared/media:/app/shared/media
      - ./shared/static:/app/shared/static
      - ./shared/templates:/app/shared/templates

volumes:
  yb_hackathon-postgresql:
