"""Introduce detections models

Revision ID: 0e8b04c93d11
Revises: e6090a546ec3
Create Date: 2019-11-15 15:54:20.235811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e8b04c93d11'
down_revision = 'e6090a546ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections_detectionobject',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections_transaction',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('detection_object_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', 'REJECTION', name='transactiontype'), nullable=True),
    sa.ForeignKeyConstraint(['detection_object_id'], ['detections_detectionobject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections_transaction')
    op.drop_table('detections_detectionobject')
    # ### end Alembic commands ###
