"""add_reference_to_users_user_model_in_transaction

Revision ID: 3ac614d3736b
Revises: 0e8b04c93d11
Create Date: 2019-11-15 15:58:09.982952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ac614d3736b'
down_revision = '0e8b04c93d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections_transaction', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'detections_transaction', 'users_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detections_transaction', type_='foreignkey')
    op.drop_column('detections_transaction', 'user_id')
    # ### end Alembic commands ###
