"""rename_games_answer_is_valid_to_is_correct

Revision ID: 3fb5ab21c9c5
Revises: 4571e56c6cec
Create Date: 2019-11-15 19:07:13.194623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb5ab21c9c5'
down_revision = '4571e56c6cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_answer', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.drop_column('games_answer', 'is_valid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_answer', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('games_answer', 'is_correct')
    # ### end Alembic commands ###
