"""add_image_to_detections_detection_object

Revision ID: 447bf2e618da
Revises: a1f140bd598c
Create Date: 2019-11-16 00:10:29.219075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447bf2e618da'
down_revision = 'a1f140bd598c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections_detectionobject', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'detections_detectionobject', ['image_filename'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detections_detectionobject', type_='unique')
    op.drop_column('detections_detectionobject', 'image_filename')
    # ### end Alembic commands ###
