"""remove_games_question_correct_answer_FK

Revision ID: 4571e56c6cec
Revises: 531bb7ca23fe
Create Date: 2019-11-15 18:56:53.768408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4571e56c6cec'
down_revision = '531bb7ca23fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_answer', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.alter_column('games_question', 'reward',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('games_question_correct_answer_id_fkey', 'games_question', type_='foreignkey')
    op.drop_column('games_question', 'correct_answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_question', sa.Column('correct_answer_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('games_question_correct_answer_id_fkey', 'games_question', 'games_answer', ['correct_answer_id'], ['id'])
    op.alter_column('games_question', 'reward',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('games_answer', 'is_valid')
    # ### end Alembic commands ###
