"""add_games_answer_model

Revision ID: 531bb7ca23fe
Revises: 572d0e5ce9e7
Create Date: 2019-11-15 18:43:40.635328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '531bb7ca23fe'
down_revision = '572d0e5ce9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_answer',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('question_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['games_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games_question', sa.Column('correct_answer_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('games_question', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'games_question', 'games_answer', ['correct_answer_id'], ['id'])
    op.drop_column('games_question', 'correct_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_question', sa.Column('correct_answer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games_question', type_='foreignkey')
    op.alter_column('games_question', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('games_question', 'correct_answer_id')
    op.drop_table('games_answer')
    # ### end Alembic commands ###
