"""make_detections_detection_object_label_unique

Revision ID: 567182fa0083
Revises: 447bf2e618da
Create Date: 2019-11-16 01:33:05.373476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567182fa0083'
down_revision = '447bf2e618da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'detections_detectionobject', ['label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detections_detectionobject', type_='unique')
    # ### end Alembic commands ###
