"""add images to games question model

Revision ID: 5e5741928139
Revises: 3fb5ab21c9c5
Create Date: 2019-11-15 19:55:51.745153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e5741928139'
down_revision = '3fb5ab21c9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_answer')
    op.drop_table('games_question')
    op.drop_constraint('detections_detectionobject_label_key', 'detections_detectionobject', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('detections_detectionobject_label_key', 'detections_detectionobject', ['label'])
    op.create_table('games_question',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reward', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='games_question_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('games_answer',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('question_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['games_question.id'], name='games_answer_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_answer_pkey')
    )
    # ### end Alembic commands ###
