"""refactor_games_question_image

Revision ID: 7dbf3e5254f9
Revises: 5e5741928139
Create Date: 2019-11-15 20:38:07.949621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dbf3e5254f9'
down_revision = '5e5741928139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_question',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_filename')
    )
    op.create_table('games_answer',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('question_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['games_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_answer')
    op.drop_table('games_question')
    # ### end Alembic commands ###
