"""Clean users.User model

Revision ID: e6090a546ec3
Revises: b791c8e8bf6e
Create Date: 2019-11-15 13:51:32.092251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6090a546ec3'
down_revision = 'b791c8e8bf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('users_user_email_key', 'users_user', type_='unique')
    op.drop_column('users_user', 'last_name')
    op.drop_column('users_user', 'email')
    op.drop_column('users_user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_user', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users_user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users_user', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_user_email_key', 'users_user', ['email'])
    op.alter_column('users_user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
